name: face_camera
description: A Flutter camera plugin that detects faces in real-time. In addition it can capture automatically once a face is detected, This can be handy while taking a selfie during kyc.
version: 0.0.3
homepage: https://github.com/Conezi/face_camera

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.9.7+1
  google_mlkit_face_detection: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.conezi.face_camera
        pluginClass: FaceCameraPlugin
      ios:
        pluginClass: FaceCameraPlugin